Task tool_emailutils\task\update_suppression_list should gracefully fail
catalyst/moodle-tool_emailutils pull request #54
Opened 2024-10-22 07:24 UTC by waleedhassan5

Fixed an Issue raised about the aws suppression list update so that it doesn't throw any exceptions if it's not enabled and doesn't cause any noise.

2024-10-22 07:38 UTC, marxjohnson requested changes
Hi Waleed,
Generally this looks like a good solution. Having it disabled by default will prevent errors where it is not being used, and having a debugging message when the configuration is not correct will help diagnose why the task is not working if it is enabled but fails.

Just a few small comments to tidy up.

2024-10-22 07:38 UTC, marxjohnson commented on classes/task/update_suppression_list.php
> +                debugging('AWS credentials are not configured.', DEBUG_NORMAL);
DEBUG_NORMAL is the default level, so you don't need to specify it here.

2024-10-22 07:38 UTC, marxjohnson commented on classes/task/update_suppression_list.php
> +                debugging('AWS credentials are not configured.', DEBUG_NORMAL);
It looks like this is the same for all `debugging` calls added in this commit.

2024-10-22 07:38 UTC, marxjohnson commented on tests/suppressionlist_test.php
You should also add a test to cover running the task when the suppression list is not enabled (you should get no output from `execute`, and the table should be empty).

2024-10-22 08:07 UTC, marxjohnson commented on tests/suppressionlist_test.php
> +        $task = new \tool_emailutils\task\update_suppression_list();
You need to do the same mocking you do in the previous test, so that it has records to potentially insert into the database, otherwise the check that the table is empty will pass regardless of whether the setting is enabled or not.

2024-10-23 03:55 UTC, brendanheywood commented
@waleedhassan5  Can you always please cross link the issue number in the commit AND in the pull request description so that github does all its nice magic linking.

https://docs.github.com/en/enterprise-server@3.12/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests

2024-10-23 07:55 UTC, waleedhassan5 commented
> @waleedhassan5 Can you always please cross link the issue number in the commit AND in the pull request description so that github does all its nice magic linking.
> 
> https://docs.github.com/en/enterprise-server@3.12/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests

Sure sorry about that.

2024-10-24 12:49 UTC, marxjohnson approved these changes
Ok, this looks good now. No noise unless the feature is enabled, and it will output a message but still succeed if the task is enabled but credentials aren't configured correctly.

2024-10-24 12:50 UTC, merged